name: national_assembly_france_hemicycle
description: Draw a French National Assembly. Depends on hemicycle Flutter package.
version: 0.4.3
homepage:
repository: https://github.com/1278real/national_assembly_france_hemicycle

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  #hemicycle: ^0.1.1
  hemicycle:
    git: 
      url: https://github.com/1278real/hemicycle
      ref: outer_new
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
