name: national_assembly_france_hemicycle
description: Draw a French National Assembly. Depends on hemicycle Flutter package.
version: 0.6.1
homepage:
repository: https://github.com/1278real/national_assembly_france_hemicycle

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  archive: ^3.3.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  hemicycle: ^0.3.1
  #hemicycle:
  #  git: 
  #    url: https://github.com/1278real/hemicycle
  #    ref: hilite_frondeurs
  http: ^0.13.4
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
